/*
	Compare the measure values by categories. 
	It helps us understand the importance of different categories
	'Measure' By 'Dimension'
*/

-- Find total customers by countries

	SELECT
	  country,                              
	  COUNT(customer_key) AS Total_customers -- count customers
	FROM Gold.dim_customers
	GROUP BY country
	ORDER BY Total_customers DESC;          -- highest first


	-- Find total customers by gender

	SELECT
		gender,
		COUNT(customer_key) AS total_customers -- count customers
	FROM gold.dim_customers
	GROUP BY gender
	ORDER BY total_customers DESC;          -- highest first


	-- Find total products by category
	
	SELECT
		category,
		COUNT(product_key) AS Total_Products -- count products
	FROM Gold.dim_products
	GROUP BY category
	ORDER BY Total_Products DESC;           -- highest first


	-- What is the average costs in each category?

	SELECT
		category,
		AVG(cost) AS Avg_Costs               -- average cost
	FROM Gold.dim_products
	GROUP BY category
	ORDER BY Avg_Costs DESC;                -- highest first


	-- What is the total revenue generated for each category?

	SELECT 
		p.category,
		SUM(f.sales_amount) AS Total_Revenue -- total revenue
	FROM Gold.fact_sales AS f
	LEFT JOIN Gold.dim_products AS p
	ON p.product_key = f.product_key        -- join sales with product
	GROUP BY p.category
	ORDER BY Total_revenue DESC;            -- highest first


	-- What is the total revenue generated by each customer?

	SELECT
		c.customer_key,
		c.first_name,
		c.last_name,
		SUM(f.sales_amount) AS Total_revenue -- total revenue
	FROM Gold.fact_sales AS f
	LEFT JOIN Gold.dim_customers AS c
	ON c.customer_key = f.customer_key     -- join sales with customer
	GROUP BY
		c.customer_key,
		c.first_name,
		c.last_name
	ORDER BY Total_revenue DESC;           -- highest first


	-- What is the distribution of sold items across countries?

	SELECT
		c.country,
		SUM(f.quantity) AS Total_Sold_Items -- total quantity sold
	FROM Gold.fact_sales AS f
	LEFT JOIN Gold.dim_customers AS c
	ON c.customer_key = f.customer_key     -- join sales with customer
	GROUP BY
		c.country
	ORDER BY Total_Sold_Items DESC;        -- highest first